spring:
  application:
    name: Auth
  datasource:
    url: jdbc:postgresql://localhost:5433/auth
    username: postgres
    password: password
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email, phone
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
        provider:
          google:
            issuer-uri: https://accounts.google.com

frontend:
  base-url: http://localhost:3000

jwt:
  secret: ${JWT_SECRET}
  lifetime: 1h

encryption:
  key: ${ENCRYPTION_KEY}

server:
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG